// <auto-generated /> Disable StyleCop on this file
namespace SampleNamespace
{
    public class NullConditionalOperator
    {
        public static int GetHash(object o)
        {
            return o?.GetHashCode() ?? 0;
        }

        public static int GetLength<T>(T[] arr)
        {
            return arr?.Length ?? 0;
        }

        private object[] _array;

        public object NeverNull => _array?[0] ?? new object();
    }
}