// <auto-generated /> Disable StyleCop on this file
using static System.Console;
using static System.Math;

namespace SampleNamespace
{
	public class StaticNamespaces
	{
		static double GetSquarerootOf(double d)
		{
			return Sqrt(d);
		}

		static void Log(string s) => WriteLine(s);
	}
}