// <auto-generated /> Disable StyleCop on this file
using System.Linq;
using static System.Linq.Enumerable;

namespace SampleNamespace
{
	public class StaticExtensionMethods
	{
		static void GetRange(int s, int e)
		{
			// not an extension method, so ok
			var range = Range(s, e);
			// var odd = Where(range, int => if % 2 == 1); - error, as is extension method
			var even = range.Where(i => i % 2 == 0); // Ok
		}
	}
}