// <auto-generated /> Disable StyleCop on this file
namespace SampleNamespace
{
    public class PropertyCode
    {
        #region Properties

        /// <summary>
        /// NArrange used to alter this property to be multipline, but I despise that, so from now on it is always set to inline.
        /// Code implemented from my blog post http://mastasoftware.net/2014/08/20/il-disassemble-for-fun/
        /// </summary>
        public bool Property { get; set; }

        #endregion Properties
    }
}